# Generated by Django 5.1.1 on 2024-09-24 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

def create_loan_types(apps, schema_editor):
    LoanType = apps.get_model('api', 'LoanType')
    
    loan_types = [
        {'name': 'Empréstimo Avulso', 'factor': 0.0},    # Emprestimo Avulso sem insidio fiscal
        {'name': 'Empréstimo Pessoal', 'factor': 0.0005},  # 0.05% ao dia (~1.5% ao mês)
        {'name': 'Empréstimo Consignado', 'factor': 0.0002},  # 0.02% ao dia (~0.6% ao mês)
        {'name': 'Financiamento Imobiliário', 'factor': 0.00015},  # 0.015% ao dia (~0.45% ao mês)
        {'name': 'Financiamento de Veículos', 'factor': 0.0003},  # 0.03% ao dia (~0.9% ao mês)
        {'name': 'Empréstimo com Garantia de Imóvel', 'factor': 0.00025},  # 0.025% ao dia (~0.75% ao mês)
    ]
    
    for data in loan_types:
        LoanType.objects.create(**data)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('factor', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
            ],
            options={
                'verbose_name': 'Loan Type',
                'verbose_name_plural': 'Loan Types',
                'db_table': 'loan_types',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('date', models.DateField(auto_now_add=True)),
                ('bank', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='api.loantype')),
            ],
            options={
                'verbose_name': 'loan',
                'verbose_name_plural': 'Loans',
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.loan')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
            },
        ),
        migrations.RunPython(create_loan_types),
    ]
